name: MISTER IASA GH-pages CI

on:
  push:
    branches: 
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Make folders
        run: |
          mkdir process
          mkdir build
      - name: Clone branches
        run: |
          git clone "https://${{ secrets.GH_PAT }}@github.com/IASAStudentCouncil/mister_iasa.git" --branch dev --single-branch ./process
          git clone "https://${{ secrets.GH_PAT }}@github.com/IASAStudentCouncil/mister_iasa.git" --branch gh-pages --single-branch ./build
      - name: Generate static pages
        run: |
          cd ./process
          npm install
          npm run build
      - run: cd ../
      - run: cp -r ./process/build ./
      - run: cd ./build
      - name: Set git config and add changes
        run: |
          git config --global user.email "${GITHUB_ACTOR}@https://users.noreply.github.com/"
          git config --global user.name "${GITHUB_ACTOR}"
          git add --all
        working-directory: ./build
      - name: Push and send notification
        run: |
          COMMIT_MESSAGE="Update pages on $(date +'%Y-%m-%d %H:%M:%S')"
          git diff-index --quiet --cached HEAD -- && echo "No changes!" && exit 0 || echo $COMMIT_MESSAGE
          # Only if repo have changes
          git commit -m "${COMMIT_MESSAGE}"
          git push --force https://${{ secrets.GH_PAT }}@github.com/IASAStudentCouncil/mister_iasa.git
        working-directory: ./build
